version: '3'

services:
  kubernetes:
    build:
      context: kubernetes
    container_name: kubernetes
    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081"]
      interval: 5s
      timeout: 20s
      retries: 10

  coredns:
    image: coredns/coredns:1.4.0
    container_name: coredns
    command: ["-conf", "/Corefile"]
    network_mode: host
    depends_on:
      - kubernetes

    volumes:
      - ./Corefile-dnsperf:/Corefile

  go-dnsperf:
    image: mikkeloscar/go-dnsperf:latest
    entrypoint: ["sh", "-c", "sleep 10 && /go-dnsperf"]
    network_mode: host
    depends_on:
      - kubernetes
      - coredns
    volumes:
      - ./resolv.conf:/etc/resolv.conf
