version: '3'

services:
  coredns:
    image: coredns/coredns:1.4.0
    container_name: coredns
    command: ["-dns.port","1053"]
      
    ports:
      - 1053:1053

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1053"]
      interval: 5s
      timeout: 10s
      retries: 3
      
  dnsperf:
    build:
      context: dnsperf
    container_name: dnsperf
    command: ["/bin/bash", "-c", "/wait-for.sh coredns:1053 && dnsperf -n 4 -d /top-100k.dnsperf -p 1053 -s coredns"]
    depends_on:
      - coredns
    links:
      - coredns:coredns
