version: '3'

services:
  kubernetes:
    build:
      context: kubernetes
    container_name: kubernetes
    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081"]
      interval: 5s
      timeout: 10s
      retries: 3

  coredns:
    image: coredns/coredns:1.4.0
    container_name: coredns
    command: ["-conf", "/Corefile"]
    network_mode: host
    depends_on:
      - kubernetes
      
    volumes:
      - ./Corefile:/Corefile

  dnsperf:
    build:
      context: dnsperf
    container_name: dnsperf
    command: ["/bin/bash", "-c", "/wait-for.sh localhost:1053 && dnsperf -n 4 -d /top-100k.dnsperf -p 1053 -s 127.0.0.1"]
    network_mode: host
    depends_on:
      - kubernetes
      - coredns

#  dnsperf:
#    image: mikkeloscar/go-dnsperf:latest
#    container_name: go-dnsperf
#    entrypoint: ["bash", "-c", "sleep 3600 && /go-dnsperf"]
#    network_mode: host
#    depends_on:
#      - kubernetes
#      - coredns
#    volumes:
#      - ./resolv.conf:/etc/resolv.conf
